tasks:
  - delay: 1
    action: "all"
  - delay: 5
    action: "all"
  - delay: 18
    action: "all"
  - delay: 24
    action: "all"
  - delay: 30
    action: "master"
  - delay: 40
    action: "master"
  - delay: 45
    action: "slave"
  - delay: 50
    action: "slave"
  - delay: 55
    action: "all"


workload:
  name: "1kb5p5c60min"
  messageSize: 1
  producers: 5
  consumers: 5
  producerRate: 100000
  warmupDurationMinutes: 0
  runtimeDurtationMinutes: 60
  outputFile: "1kb5p5c60min.txt"
  seed: 28072000

connectionConfig:
  amqpUris:
    - "amqp://rabbitmq:password@loadbalancer:5672"
  primaryBrokerUri: "amqp://rabbitmq:password@loadbalancer:5672"

serverUrls:
  - "http://masternode:5000"
  - "http://slavenode0:5000"
  - "http://slavenode1:5000"
