tasks:
  - delay: 12
    action: "slave"
  - delay: 14
    action: "master"
  - delay: 18
    action: "all"
  - delay: 25
    action: "all"
  - delay: 30
    action: "master"
  - delay: 40
    action: "master"
  - delay: 45
    action: "slave"
  - delay: 50
    action: "slave"
  - delay: 55
    action: "all"


workload:
  name: "1kb10p10c60min"
  messageSize: 1
  producers: 10
  consumers: 10
  producerRate: 100000
  warmupDurationMinutes: 0
  runtimeDurtationMinutes: 60
  outputFile: "1kb10p10c60min.txt"
  seed: 28072000

connectionConfig:
  amqpUris:
    - "amqp://rabbitmq:password@loadbalancer:5672"
  primaryBrokerUri: "amqp://rabbitmq:password@loadbalancer:5672"
  apiUrl: "http://loadbalancer:15672"

serverUrls:
  - "http://node0:5000"
  - "http://node1:5000"
  - "http://node2:5000"
